"""init

Revision ID: c05514599a5a
Revises: 
Create Date: 2024-02-18 12:19:56.503875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.migration import MigrationContext


# revision identifiers, used by Alembic.
revision: str = "c05514599a5a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts") as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "birthday",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )

    op.drop_index("contacts_name", table_name="contacts")
    op.create_index(op.f("contacts_email"), "contacts", ["email"], unique=False)
    op.create_index(
        op.f("contacts_first_name"), "contacts", ["first_name"], unique=False
    )
    op.create_index(op.f("contacts_last_name"), "contacts", ["last_name"], unique=False)
    op.drop_column("contacts", "name")
    op.drop_column("contacts", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts") as batch_op:
        batch_op.add_column(sa.Column("phone", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=True))

    op.drop_index(op.f("contacts_last_name"), table_name="contacts")
    op.drop_index(op.f("contacts_first_name"), table_name="contacts")
    op.drop_index(op.f("contacts_email"), table_name="contacts")
    op.create_index("contacts_name", "contacts", ["name"], unique=False)
    op.drop_column("contacts", "birthday")
    op.drop_column("contacts", "phone_number")
    op.drop_column("contacts", "last_name")
    op.drop_column("contacts", "first_name")
